name: Playwright Automation Pipeline

on:
  push:
    branches: [ main, develop ]

  workflow_dispatch:
    inputs:
      test_type:
        description: "Test Type (smoke / full)"
        required: false
        default: "smoke"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Setup Environment
        run: |
          cat <<EOF > .env
          USER_PORTAL_URL=https://www.saucedemo.com
          USER_PORTAL_USERNAME=standard_user
          USER_PORTAL_PASSWORD=secret_sauce
          TAKE_SCREENSHOTS=false
          EOF

      - name: Run Playwright Tests
        env:
          TEST_TYPE: ${{ github.event.inputs.test_type }}
        run: |
          if [ -n "$TEST_TYPE" ]; then
            npx playwright test tests/$TEST_TYPE
          else
            npx playwright test
          fi

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
